apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: conformance-pingsource
spec:
  schedule: "*/1 * * * *"
  data: '{"msg": "hello"}'
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: conformance-channel