apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: conformance-subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: conformance-channel
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: conformance-sockeye
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: conformance-sockeye