apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: conformance-trigger
spec:
  broker: conformance-broker
  subscriber:
    ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: cloudevents-player
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: cloudevents-player
