apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: conformance-trigger
spec:
  broker: conformance-broker
  subscriber:
    uri: http://events-counter-service.default.svc.cluster.local/events
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Broker
        name: conformance-broker
