apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: conformance-trigger
spec:
  broker: conformance-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: conformance-deadletter
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: conformance-deadletter
