apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: conformance-trigger-no-subscriber
spec:
  broker: conformance-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: non-existent