apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: conformance-subscription-channel-namespace
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: conformance-channel
    namespace: test
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: conformance-deadletter
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: conformance-events